---
version: 1

root:
  handlers:
    - fileHandler

handlers:
  fileHandler:
    class: logging.FileHandler
    level: INFO
    formatter: json
    filename: /var/log/uwsgi/app/husky_musher.log

formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s %(filename)s %(funcname)s %(lineno)d %(module)s %(process)d'
