name: CI

on:
  - push
  - pull_request

env:
  REDCAP_API_URL: 'https://dummy.redcap.url/api'
  FLASK_ENV: development

jobs:
  test:
    name: python=${{ matrix.python }} os=${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
        python:
          - 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade Python toolchain
        run: python3 -m pip install --upgrade pip setuptools wheel

      - name: Install Pipenv
        run: python3 -m pip install pipenv

      - name: Install Dependencies
        run: pipenv sync --dev

      - name: Run unittest
        run: pipenv run python -m unittest lib/husky_musher/tests/*
